Loading in python source files and data sets

In [2]:
import pandas as pd 
import numpy as np
HarrisPartI = pd.read_csv("HarrisPartI.csv")
HarrisPartIII = pd.read_csv("HarrisPartIII.csv")
VDB = pd.read_csv("vandenBerg_table2.csv")
Krause21 = pd.read_csv("Krause21.csv")

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.width', None)

In [6]:
harris_merged = pd.merge(HarrisPartI, HarrisPartIII, on='ID', how='outer')
display(harris_merged)

,ID,Name,RA,DEC,L,B,R_Sun,R_gc,X,Y,Z,v_r,v_r_e,v_LSR,sig_v,sig_v_e,c,r_c,r_h,mu_V,rho_0,lg_tc,lg_th
0,1636-283,ESO452-SC11,16:39:25.45,-28:23:55.3,351.91,12.10,8.3,2.1,8.0,-1.1,1.7,NaN,NaN,NaN,NaN,NaN,1.00,0.50,0.50,20.75,2.50,8.07,7.87
1,2MS-GC01,2MASS-GC01,18:08:21.81,-19:49:47,10.48,0.11,3.6,4.5,3.5,0.7,0.0,NaN,NaN,NaN,NaN,NaN,0.85,0.85,1.65,NaN,NaN,NaN,8.43
2,2MS-GC02,2MASS-GC02,18:09:36.50,-20:46:44,9.79,-0.61,4.9,3.2,4.9,0.8,-0.1,-238.0,36.0,-227.4,NaN,NaN,0.95,0.55,0.55,NaN,NaN,NaN,7.72
3,AM 1,E 1,03:55:02.3,-49:36:55,258.34,-48.47,123.3,124.6,-16.5,-80.1,-92.3,116.0,20.0,101.3,NaN,NaN,1.36,0.17,0.41,23.62,0.03,8.96,9.61
4,AM 4,NaN,13:56:21.7,-27:10:03,320.28,33.51,32.2,27.8,20.7,-17.2,17.8,NaN,NaN,NaN,NaN,NaN,0.70,0.41,0.43,24.75,-0.05,8.42,8.32
5,Arp 2,NaN,19:28:44.11,-30:21:20.3,8.55,-20.79,28.6,21.4,26.4,4.0,-10.2,115.0,10.0,122.4,NaN,NaN,0.88,1.19,1.77,24.26,-0.25,9.39,9.70
6,BH 176,NaN,15:39:07.45,-50:03:09.8,328.41,4.34,18.9,12.9,16.1,-9.9,1.4,NaN,NaN,NaN,NaN,NaN,0.85,0.90,0.90,23.36,0.97,9.14,8.79
7,BH 261,AL 3,18:14:06.6,-28:38:06,3.36,-5.27,6.5,1.7,6.5,0.4,-0.6,NaN,NaN,NaN,NaN,NaN,1.00,0.40,0.55,NaN,NaN,NaN,7.80
8,Djorg 1,NaN,17:47:28.3,-33:03:56,356.69,-2.47,13.7,5.7,13.6,-0.8,-0.6,-362.4,3.6,-355.0,NaN,NaN,1.50,0.50,1.59,23.10,2.68,8.71,0.00
9,Djorg 2,ESO456-SC38,18:01:49.1,-27:49:33,2.77,-2.50,6.3,1.8,6.2,0.3,-0.3,NaN,NaN,NaN,NaN,NaN,1.50,0.33,1.05,19.50,3.85,7.73,0.00
10,E 3,NaN,09:20:57.07,-77:16:54.8,292.27,-19.02,8.1,9.1,2.9,-7.1,-2.6,NaN,NaN,NaN,NaN,NaN,0.75,1.87,2.10,23.10,0.84,8.93,8.80
11,ESO-SC06,ESO280-SC06,18:09:06.0,-46:25:23,346.90,-12.57,21.4,14.0,20.4,-4.7,-4.7,NaN,NaN,NaN,NaN,NaN,0.90,0.60,1.05,NaN,NaN,NaN,9.10
12,Eridanus,NaN,04:24:44.5,-21:11:13,218.10,-41.33,90.1,95.0,-53.2,-41.7,-59.5,-23.6,2.1,-39.1,NaN,NaN,1.10,0.25,0.46,22.81,0.38,9.18,9.54
13,FSR 1735,NaN,16:52:10.6,-47:03:29,339.19,-1.85,9.8,3.7,9.1,-3.5,-0.3,NaN,NaN,NaN,NaN,NaN,0.56,0.39,0.34,NaN,NaN,NaN,8.11
14,GLIMPSE01,NaN,18:48:49.7,-01:29:50,31.31,-0.10,4.2,4.9,3.6,2.2,0.0,NaN,NaN,NaN,NaN,NaN,1.37,0.59,0.65,NaN,NaN,NaN,7.89
15,GLIMPSE02,NaN,18:18:30.5,-16:58:38,14.14,-0.64,5.5,3.0,5.4,1.4,-0.1,NaN,NaN,NaN,NaN,NaN,1.33,0.70,NaN,NaN,NaN,NaN,NaN
16,HP 1,BH 229,17:31:05.2,-29:58:54,357.44,2.12,8.2,0.5,8.2,-0.4,0.3,45.8,0.7,54.0,NaN,NaN,2.50,0.03,3.10,21.29,4.33,5.03,9.44
17,IC 1257,NaN,17:27:08.5,-07:05:35,16.54,15.15,25.0,17.9,23.2,6.9,6.5,-140.2,2.1,-127.0,NaN,NaN,1.55,0.25,1.40,NaN,NaN,NaN,9.60
18,IC 1276,Pal 7,18:10:44.20,-07:12:27.4,21.83,5.67,5.4,3.7,5.0,2.0,0.5,155.7,1.3,169.2,NaN,NaN,1.33,1.01,2.38,21.60,2.78,8.46,9.03
19,IC 4499,NaN,15:00:18.45,-82:12:49.3,307.35,-20.47,18.8,15.7,10.7,-14.0,-6.6,31.5,0.2,24.1,2.5,0.5,1.21,0.84,1.71,20.90,1.55,9.21,9.73
20,Ko 1,NaN,11:59:18.5,+12:15:36,260.99,70.75,48.3,49.3,-2.5,-15.7,45.6,NaN,NaN,NaN,NaN,NaN,0.50,0.33,0.26,NaN,NaN,NaN,8.62
21,Ko 2,NaN,07:58:17.0,+26:15:18,195.12,25.54,34.7,41.9,-30.2,-8.2,15.0,NaN,NaN,NaN,NaN,NaN,0.50,0.25,0.21,NaN,NaN,NaN,7.70
22,Liller 1,NaN,17:33:24.50,-33:23:20.4,354.84,-0.16,8.2,0.8,8.2,-0.7,0.0,52.0,15.0,59.2,NaN,NaN,2.30,0.06,NaN,24.00,5.28,6.62,0.00
23,Lynga 7,BH184,16:11:03.65,-55:19:04.0,328.77,-2.80,8.0,4.3,6.8,-4.1,-0.4,8.0,5.0,8.0,NaN,NaN,0.95,0.90,1.20,NaN,NaN,NaN,8.83
24,NGC 104,47 Tuc,00:24:05.67,-72:04:52.6,305.89,-44.89,4.5,7.4,1.9,-2.6,-3.1,-18.0,0.1,-26.7,11.0,0.3,2.07,0.36,3.17,14.38,4.88,7.84,9.55
25,NGC 1261,NaN,03:12:16.21,-55:12:58.4,270.54,-52.12,16.3,18.1,0.1,-10.0,-12.9,68.2,4.6,54.9,NaN,NaN,1.16,0.35,0.68,17.73,2.99,8.59,9.12
26,NGC 1851,NaN,05:14:06.76,-40:02:47.6,244.51,-35.03,12.1,16.6,-4.2,-8.9,-6.9,320.5,0.6,303.8,10.4,0.5,1.86,0.09,0.51,14.25,5.09,7.43,8.82
27,NGC 1904,M 79,05:24:11.09,-24:31:29.0,227.23,-29.35,12.9,18.8,-7.7,-8.3,-6.3,205.8,0.4,189.0,5.3,0.4,1.70,0.16,0.65,16.02,4.08,7.83,8.95
28,NGC 2298,NaN,06:48:59.41,-36:00:19.1,245.63,-16.00,10.8,15.8,-4.3,-9.4,-3.0,148.9,1.2,132.0,NaN,NaN,1.38,0.31,0.98,18.90,2.90,7.91,8.84
29,NGC 2419,NaN,07:38:08.47,+38:52:56.8,180.37,25.24,82.6,89.9,-74.7,-0.5,35.2,-20.2,0.5,-25.2,4.0,0.6,1.37,0.32,0.89,19.67,1.62,9.87,10.63
30,NGC 2808,NaN,09:12:03.10,-64:51:48.6,282.19,-11.25,9.6,11.1,2.0,-9.2,-1.9,101.6,0.7,89.2,13.4,1.2,1.56,0.25,0.80,15.08,4.66,8.24,9.15
31,NGC 288,NaN,00:52:45.24,-26:34:57.4,152.30,-89.38,8.9,12.0,-0.1,0.0,-8.9,-45.4,0.2,-51.9,2.9,0.3,0.99,1.35,2.23,20.05,1.78,8.99,9.32
32,NGC 3201,NaN,10:17:36.82,-46:24:44.9,277.23,8.64,4.9,8.8,0.6,-4.8,0.7,494.0,0.2,482.9,5.0,0.2,1.29,1.30,3.10,19.00,2.71,8.61,9.27
33,NGC 362,NaN,01:03:14.26,-70:50:55.6,301.53,-46.25,8.6,9.4,3.1,-5.1,-6.2,223.5,0.5,214.0,6.4,0.3,1.76,0.18,0.82,14.80,4.74,7.76,8.93
34,NGC 4147,NaN,12:10:06.30,+18:32:33.5,252.85,77.19,19.3,21.4,-1.3,-4.1,18.8,183.2,0.7,186.1,2.6,0.7,1.83,0.09,0.48,17.38,3.63,7.41,8.74
35,NGC 4372,NaN,12:25:45.40,-72:39:32.4,300.99,-9.88,5.8,7.1,2.9,-4.9,-1.0,72.3,1.2,64.2,NaN,NaN,1.30,1.75,3.91,20.58,2.06,8.88,9.59
36,NGC 4590,M 68,12:39:27.98,-26:44:38.6,299.63,36.05,10.3,10.2,4.1,-7.2,6.0,-94.7,0.2,-96.8,2.5,0.4,1.41,0.58,1.51,18.81,2.57,8.45,9.27
37,NGC 4833,NaN,12:59:33.92,-70:52:35.4,303.60,-8.02,6.6,7.0,3.6,-5.4,-0.9,200.2,1.2,192.9,NaN,NaN,1.25,1.00,2.41,18.48,3.00,8.78,9.42
38,NGC 5024,M 53,13:12:55.25,+18:10:05.4,332.96,79.76,17.9,18.4,2.8,-1.4,17.6,-62.9,0.3,-56.2,4.4,0.9,1.72,0.35,1.31,17.38,3.07,8.73,9.76
39,NGC 5053,NaN,13:16:27.09,+17:42:00.9,335.70,78.95,17.4,17.8,3.0,-1.4,17.1,44.0,0.4,50.9,1.4,0.2,0.74,2.08,2.61,22.03,0.54,9.81,9.87
40,NGC 5139,omega Cen,13:26:47.24,-47:28:46.5,309.10,14.97,5.2,6.4,3.1,-3.9,1.3,232.1,0.1,228.9,16.8,0.3,1.31,2.37,5.00,16.81,3.15,9.60,10.09
41,NGC 5272,M 3,13:42:11.62,+28:22:38.2,42.22,78.71,10.2,12.0,1.5,1.3,10.0,-147.6,0.2,-138.3,5.5,0.3,1.89,0.37,2.31,16.64,3.57,8.31,9.79
42,NGC 5286,NaN,13:46:26.81,-51:22:27.3,311.61,10.57,11.7,8.9,7.6,-8.6,2.1,57.4,1.5,54.3,8.1,1.0,1.41,0.28,0.73,16.22,4.10,8.40,9.11
43,NGC 5466,NaN,14:05:27.29,+28:32:04.0,42.15,73.59,16.0,16.3,3.3,3.0,15.3,110.7,0.2,121.2,1.7,0.2,1.04,1.43,2.30,21.61,0.84,9.35,9.76
44,NGC 5634,NaN,14:29:37.23,-05:58:35.1,342.21,49.26,25.2,21.2,15.7,-5.0,19.1,-45.1,6.6,-37.5,NaN,NaN,2.07,0.09,0.86,17.20,3.63,7.67,9.54
45,NGC 5694,NaN,14:39:36.29,-26:32:20.2,331.06,30.36,35.0,29.4,26.4,-14.6,17.7,-140.3,0.8,-136.2,5.8,0.8,1.89,0.06,0.40,16.51,3.95,7.85,9.27
46,NGC 5824,NaN,15:03:58.63,-33:04:05.6,332.56,22.07,32.1,25.9,26.4,-13.7,12.1,-27.5,1.5,-23.8,11.6,0.5,1.98,0.06,0.45,15.18,4.61,7.91,9.47
47,NGC 5897,NaN,15:17:24.50,-21:00:37.0,342.95,30.29,12.5,7.4,10.3,-3.2,6.3,101.5,1.0,108.4,NaN,NaN,0.86,1.40,2.06,20.53,1.53,9.33,9.57
48,NGC 5904,M 5,15:18:33.22,+02:04:51.7,3.86,46.80,7.5,6.2,5.1,0.3,5.5,53.2,0.4,64.3,5.5,0.4,1.73,0.44,1.77,16.09,3.88,8.28,9.41
49,NGC 5927,NaN,15:28:00.69,-50:40:22.9,326.60,4.86,7.7,4.6,6.4,-4.2,0.7,-107.5,0.9,-107.2,NaN,NaN,1.60,0.42,1.10,16.91,4.09,8.39,8.94
50,NGC 5946,NaN,15:35:28.52,-50:39:34.8,327.58,4.19,10.6,5.8,8.9,-5.6,0.8,128.4,1.8,128.9,4.0,2.9,2.50,0.08,0.89,17.19,4.68,6.90,8.91
51,NGC 5986,NaN,15:46:03.00,-37:47:11.1,337.02,13.27,10.4,4.8,9.3,-4.0,2.4,88.9,3.7,92.9,NaN,NaN,1.23,0.47,0.98,17.67,3.41,8.58,9.18
52,NGC 6093,M 80,16:17:02.41,-22:58:33.9,352.67,19.46,10.0,3.8,9.4,-1.2,3.3,8.1,1.5,16.7,12.4,0.6,1.68,0.15,0.61,15.11,4.79,7.78,8.80
53,NGC 6101,NaN,16:25:48.12,-72:12:07.9,317.74,-15.82,15.4,11.2,11.0,-10.0,-4.2,361.4,1.7,357.0,NaN,NaN,0.80,0.97,1.05,20.29,1.65,9.21,9.22
54,NGC 6121,M 4,16:23:35.22,-26:31:32.7,350.97,15.97,2.2,5.9,2.1,-0.3,0.6,70.7,0.2,78.6,4.0,0.2,1.65,1.16,4.33,17.95,3.64,7.90,8.93
55,NGC 6139,NaN,16:27:40.37,-38:50:55.5,342.37,6.94,10.1,3.6,9.6,-3.0,1.2,6.7,6.0,11.5,NaN,NaN,1.86,0.15,0.85,17.20,4.67,7.66,9.05
56,NGC 6144,NaN,16:27:13.86,-26:01:24.6,351.93,15.70,8.9,2.7,8.5,-1.2,2.4,193.8,0.6,201.9,NaN,NaN,1.55,0.94,1.63,20.05,2.31,8.78,9.14
57,NGC 6171,M 107,16:32:31.86,-13:03:13.6,3.37,23.01,6.4,3.3,5.9,0.3,2.5,-34.1,0.3,-23.0,4.1,0.3,1.53,0.56,1.73,18.94,3.08,8.06,9.00
58,NGC 6205,M 13,16:41:41.24,+36:27:35.5,59.01,40.91,7.1,8.4,2.8,4.6,4.7,-244.2,0.2,-228.0,7.1,0.4,1.53,0.62,1.69,16.59,3.55,8.51,9.30
59,NGC 6218,M 12,16:47:14.18,-01:56:54.7,15.72,26.31,4.8,4.5,4.2,1.2,2.1,-41.4,0.2,-27.9,4.5,0.4,1.34,0.79,1.77,18.10,3.23,8.19,8.87
60,NGC 6229,NaN,16:46:58.79,+47:31:39.9,73.64,40.31,30.5,29.8,6.5,22.3,19.7,-154.2,7.6,-138.4,NaN,NaN,1.50,0.12,0.36,16.77,3.54,8.30,9.15
61,NGC 6235,NaN,16:53:25.31,-22:10:38.8,358.92,13.52,11.5,4.2,11.2,-0.2,2.7,87.3,3.4,96.8,NaN,NaN,1.53,0.33,1.00,19.12,2.97,8.08,8.89
62,NGC 6254,M 10,16:57:09.05,-04:06:01.1,15.14,23.08,4.4,4.6,3.9,1.1,1.7,75.2,0.7,88.5,6.6,0.8,1.38,0.77,1.95,17.70,3.54,8.21,8.90
63,NGC 6256,NaN,16:59:32.62,-37:07:17.0,347.79,3.31,10.3,3.0,10.0,-2.2,0.6,-101.4,1.9,-95.6,6.6,2.6,2.50,0.02,0.86,17.89,5.59,5.82,8.86
64,NGC 6266,M 62,17:01:12.80,-30:06:49.4,353.57,7.32,6.8,1.7,6.7,-0.8,0.9,-70.1,1.4,-62.3,14.3,0.4,1.71,0.22,0.92,15.10,5.16,7.90,8.98
65,NGC 6273,M 19,17:02:37.80,-26:16:04.7,356.87,9.38,8.8,1.7,8.7,-0.5,1.4,135.0,4.1,143.8,NaN,NaN,1.53,0.43,1.32,16.77,3.98,8.52,9.38
66,NGC 6284,NaN,17:04:28.51,-24:45:53.5,358.35,9.94,15.3,7.5,15.0,-0.4,2.6,27.5,1.7,36.7,6.3,0.9,2.50,0.07,0.66,16.35,4.55,7.24,9.09
67,NGC 6287,NaN,17:05:09.13,-22:42:30.1,0.13,11.02,9.4,2.1,9.2,0.0,1.8,-288.7,3.5,-279.1,NaN,NaN,1.38,0.29,0.74,18.32,3.78,8.06,8.75
68,NGC 6293,NaN,17:10:10.20,-26:34:55.5,357.62,7.83,9.5,1.9,9.4,-0.4,1.3,-146.2,1.7,-137.4,7.7,1.3,2.50,0.05,0.89,15.72,5.31,6.38,8.94
69,NGC 6304,NaN,17:14:32.25,-29:27:43.3,355.83,5.38,5.9,2.3,5.8,-0.4,0.6,-107.3,3.6,-99.3,NaN,NaN,1.80,0.21,1.42,17.20,4.49,7.36,8.85
70,NGC 6316,NaN,17:16:37.30,-28:08:24.4,357.18,5.76,10.4,2.6,10.4,-0.5,1.0,71.4,8.9,79.9,NaN,NaN,1.65,0.17,0.65,17.44,4.23,7.71,8.89
71,NGC 6325,NaN,17:17:59.21,-23:45:57.6,0.97,8.00,7.8,1.1,7.7,0.1,1.1,29.8,1.8,39.3,5.9,1.3,2.50,0.03,0.63,17.56,5.52,5.73,8.45
72,NGC 6333,M 9,17:19:11.26,-18:30:57.4,5.54,10.71,7.9,1.7,7.7,0.7,1.5,229.1,7.0,239.8,NaN,NaN,1.25,0.45,0.96,17.39,3.78,8.36,8.90
73,NGC 6341,M 92,17:17:07.39,+43:08:09.4,68.34,34.86,8.3,9.6,2.5,6.3,4.7,-120.0,0.1,-103.5,6.0,0.4,1.68,0.26,1.02,15.47,4.30,7.96,9.02
74,NGC 6342,NaN,17:21:10.08,-19:35:14.7,4.90,9.72,8.5,1.7,8.4,0.7,1.4,115.7,1.4,126.3,5.2,2.1,2.50,0.05,0.73,16.97,4.97,6.16,8.51
75,NGC 6352,NaN,17:25:29.11,-48:25:19.8,341.42,-7.17,5.6,3.3,5.3,-1.8,-0.7,-137.0,1.1,-134.1,NaN,NaN,1.10,0.83,2.05,18.17,3.17,8.46,8.92
76,NGC 6355,NaN,17:23:58.59,-26:21:12.3,359.59,5.43,9.2,1.4,9.2,-0.1,0.9,-176.9,7.1,-167.9,NaN,NaN,2.50,0.05,0.88,17.64,5.04,6.27,8.96
77,NGC 6356,NaN,17:23:34.93,-17:48:46.9,6.72,10.22,15.1,7.5,14.7,1.7,2.7,27.0,4.3,38.0,NaN,NaN,1.59,0.24,0.81,17.02,3.78,8.37,9.30
78,NGC 6362,NaN,17:31:54.99,-67:02:54.0,325.55,-17.57,7.6,5.1,6.0,-4.1,-2.3,-13.1,0.6,-15.6,2.8,0.4,1.09,1.13,2.05,19.31,2.29,8.80,9.20
79,NGC 6366,NaN,17:27:44.24,-05:04:47.5,18.41,16.04,3.5,5.0,3.2,1.1,1.0,-122.2,0.5,-108.6,1.3,0.5,0.74,2.17,2.92,21.25,2.39,8.74,8.73
80,NGC 6380,Ton 1,17:34:28.0,-39:04:09,350.18,-3.42,10.9,3.3,10.7,-1.9,-0.6,-3.6,2.5,2.1,NaN,NaN,1.55,0.34,0.74,19.89,3.73,8.40,8.86
81,NGC 6388,NaN,17:36:17.23,-44:44:07.8,345.56,-6.74,9.9,3.1,9.6,-2.5,-1.2,80.1,0.8,84.2,18.9,0.8,1.75,0.12,0.52,14.49,5.37,7.72,8.90
82,NGC 6397,NaN,17:40:42.09,-53:40:27.6,338.17,-11.96,2.3,6.0,2.1,-0.8,-0.5,18.8,0.1,20.3,4.5,0.2,2.50,0.05,2.90,15.47,5.76,4.94,8.60
83,NGC 6401,NaN,17:38:36.60,-23:54:34.2,3.45,3.98,10.6,2.7,10.5,0.6,0.7,-65.0,8.6,-55.3,NaN,NaN,1.69,0.25,1.91,18.70,3.79,7.97,9.53
84,NGC 6402,M 14,17:37:36.10,-03:14:45.3,21.32,14.81,9.3,4.0,8.3,3.3,2.4,-66.1,1.8,-52.1,NaN,NaN,0.99,0.79,1.30,18.41,3.36,9.06,9.39
85,NGC 6426,NaN,17:44:54.65,+03:10:12.5,28.09,16.23,20.6,14.4,17.4,9.3,5.8,-162.0,23.0,-146.9,NaN,NaN,1.70,0.26,0.92,20.09,2.47,8.31,9.28
86,NGC 6440,NaN,17:48:52.70,-20:21:36.9,7.73,3.80,8.5,1.3,8.4,1.1,0.6,-76.6,2.7,-65.9,NaN,NaN,1.62,0.14,0.48,17.06,5.24,7.60,8.62
87,NGC 6441,NaN,17:50:13.06,-37:03:05.2,353.53,-5.01,11.6,3.9,11.5,-1.3,-1.0,16.5,1.0,22.9,18.0,0.2,1.74,0.13,0.57,14.85,5.26,7.93,9.09
88,NGC 6453,NaN,17:50:51.70,-34:35:57.0,355.72,-3.87,11.6,3.7,11.5,-0.9,-0.8,-83.7,8.3,-76.7,NaN,NaN,2.50,0.05,0.44,17.07,4.95,6.73,8.52
89,NGC 6496,NaN,17:59:03.68,-44:15:57.4,348.03,-10.01,11.3,4.2,10.9,-2.3,-2.0,-112.7,5.7,-108.4,NaN,NaN,0.70,0.95,1.02,20.17,1.99,8.94,9.04
90,NGC 6517,NaN,18:01:50.52,-08:57:31.6,19.23,6.76,10.6,4.2,10.0,3.5,1.3,-39.6,8.0,-26.5,NaN,NaN,1.82,0.06,0.50,17.56,5.29,6.92,8.72
91,NGC 6522,NaN,18:03:34.02,-30:02:02.3,1.02,-3.93,7.7,0.6,7.7,0.1,-0.5,-21.1,3.4,-12.9,6.7,0.7,2.50,0.05,1.00,15.75,5.48,6.38,8.86
92,NGC 6528,NaN,18:04:49.64,-30:03:22.6,1.14,-4.17,7.9,0.6,7.9,0.2,-0.6,206.6,1.4,214.9,NaN,NaN,1.50,0.13,0.38,16.73,4.77,7.28,8.06
93,NGC 6535,NaN,18:03:50.51,-00:17:51.5,27.18,10.44,6.8,3.9,6.0,3.1,1.2,-215.1,0.5,-200.4,2.4,0.5,1.33,0.36,0.85,21.26,2.34,7.28,8.20
94,NGC 6539,NaN,18:04:49.68,-07:35:09.1,20.80,6.78,7.8,3.0,7.2,2.8,0.9,31.0,1.7,44.4,NaN,NaN,1.74,0.38,1.70,18.58,4.15,8.31,9.32
95,NGC 6540,Djorg 3,18:06:08.6,-27:45:55,3.29,-3.31,5.3,2.8,5.2,0.3,-0.3,-17.7,1.4,-8.8,NaN,NaN,2.50,0.03,NaN,16.40,5.85,5.40,0.00
96,NGC 6541,NaN,18:08:02.36,-43:42:53.6,349.29,-11.19,7.5,2.1,7.3,-1.4,-1.5,-158.7,2.3,-154.2,8.2,2.1,1.86,0.18,1.06,15.44,4.65,7.55,9.03
97,NGC 6544,NaN,18:07:20.58,-24:59:50.4,5.84,-2.20,3.0,5.1,2.9,0.3,-0.1,-27.3,3.9,-17.7,NaN,NaN,1.63,0.05,1.21,16.31,6.06,5.35,8.24
98,NGC 6553,NaN,18:09:17.60,-25:54:31.3,5.26,-3.03,6.0,2.2,5.9,0.5,-0.3,-3.2,1.5,6.1,NaN,NaN,1.16,0.53,1.03,18.17,3.84,8.24,8.72
99,NGC 6558,NaN,18:10:17.60,-31:45:50.0,0.20,-6.02,7.4,1.0,7.3,0.0,-0.8,-197.2,1.5,-189.4,3.1,0.9,2.50,0.03,2.15,16.48,5.35,5.71,9.12
100,NGC 6569,NaN,18:13:38.80,-31:49:36.8,0.48,-6.68,10.9,3.1,10.8,0.1,-1.3,-28.1,5.6,-20.3,NaN,NaN,1.31,0.35,0.80,18.15,3.63,8.38,9.05
101,NGC 6584,NaN,18:18:37.60,-52:12:56.8,342.14,-16.41,13.5,7.0,12.3,-4.0,-3.8,222.9,15.0,224.9,NaN,NaN,1.47,0.26,0.73,17.63,3.33,8.13,9.02
102,NGC 6624,NaN,18:23:40.51,-30:21:39.7,2.79,-7.91,7.9,1.2,7.8,0.4,-1.1,53.9,0.6,62.1,5.4,0.5,2.50,0.06,0.82,15.32,5.30,6.61,8.71
103,NGC 6626,M 28,18:24:32.81,-24:52:11.2,7.80,-5.58,5.5,2.7,5.4,0.7,-0.5,17.0,1.0,26.6,8.6,1.3,1.67,0.24,1.97,15.77,4.86,7.62,9.17
104,NGC 6637,M 69,18:31:23.10,-32:20:53.1,1.72,-10.27,8.8,1.7,8.6,0.3,-1.6,39.9,2.8,47.5,NaN,NaN,1.38,0.33,0.84,16.82,3.84,8.15,8.82
105,NGC 6638,NaN,18:30:56.10,-25:29:50.9,7.90,-7.15,9.4,2.2,9.3,1.3,-1.2,18.1,3.9,27.5,NaN,NaN,1.33,0.22,0.51,17.30,4.09,7.83,8.46
106,NGC 6642,NaN,18:31:54.10,-23:28:30.7,9.81,-6.44,8.1,1.7,8.0,1.4,-0.9,-57.2,5.4,-47.3,NaN,NaN,1.99,0.10,0.73,16.82,4.64,6.95,8.52
107,NGC 6652,NaN,18:35:45.63,-32:59:26.6,1.53,-11.38,10.0,2.7,9.8,0.3,-2.0,-111.7,5.8,-104.3,NaN,NaN,1.80,0.10,0.48,16.10,4.48,7.05,8.39
108,NGC 6656,M 22,18:36:23.94,-23:54:17.1,9.89,-7.55,3.2,4.9,3.2,0.6,-0.4,-146.3,0.2,-136.6,7.8,0.3,1.38,1.33,3.36,17.42,3.63,8.53,9.23
109,NGC 6681,M 70,18:43:12.76,-32:17:31.6,2.85,-12.51,9.0,2.2,8.8,0.4,-2.0,220.3,0.9,227.8,5.2,0.5,2.50,0.03,0.71,14.25,5.82,5.82,8.65
110,NGC 6712,NaN,18:53:04.30,-08:42:22.0,25.35,-4.32,6.9,3.5,6.3,3.0,-0.5,-107.6,0.5,-94.7,4.3,0.4,1.05,0.76,1.33,18.74,3.18,8.60,8.95
111,NGC 6715,M 54,18:55:03.33,-30:28:47.5,5.61,-14.09,26.5,18.9,25.6,2.5,-6.5,141.3,0.3,149.2,10.5,0.3,2.04,0.09,0.82,14.78,4.69,8.24,9.93
112,NGC 6717,Pal 9,18:55:06.04,-22:42:05.3,12.88,-10.90,7.1,2.4,6.8,1.6,-1.3,22.8,3.4,32.7,NaN,NaN,2.07,0.08,0.68,16.77,4.58,6.52,8.22
113,NGC 6723,NaN,18:59:33.15,-36:37:56.1,0.07,-17.30,8.7,2.6,8.3,0.0,-2.6,-94.5,3.6,-88.3,NaN,NaN,1.11,0.83,1.53,18.13,2.79,8.79,9.24
114,NGC 6749,NaN,19:05:15.3,+01:54:03,36.20,-2.21,7.9,5.0,6.4,4.7,-0.3,-61.7,2.9,-47.2,NaN,NaN,0.79,0.62,1.10,21.88,3.30,8.59,8.78
115,NGC 6752,NaN,19:10:52.11,-59:59:04.4,336.49,-25.63,4.0,5.2,3.3,-1.4,-1.7,-26.7,0.2,-27.3,4.9,0.4,2.50,0.17,1.91,14.88,5.04,6.88,8.87
116,NGC 6760,NaN,19:11:12.01,+01:01:49.7,36.11,-3.92,7.4,4.8,5.9,4.3,-0.5,-27.5,6.3,-13.2,NaN,NaN,1.65,0.34,1.27,18.66,3.89,7.96,9.01
117,NGC 6779,M 56,19:16:35.57,+30:11:00.5,62.66,8.34,9.4,9.2,4.3,8.3,1.4,-135.6,0.9,-119.1,4.0,0.6,1.38,0.44,1.10,18.08,3.28,8.33,9.01
118,NGC 6809,M 55,19:39:59.71,-30:57:53.1,8.79,-23.27,5.4,3.9,4.9,0.8,-2.1,174.7,0.3,181.8,4.0,0.3,0.93,1.80,2.83,19.36,2.22,8.90,9.29
119,NGC 6838,M 71,19:53:46.49,+18:46:45.1,56.75,-4.56,4.0,6.7,2.2,3.4,-0.3,-22.8,0.2,-7.5,2.3,0.2,1.15,0.63,1.67,19.75,2.83,7.54,8.43
120,NGC 6864,M 75,20:06:04.69,-21:55:16.2,20.30,-25.75,20.9,14.7,17.6,6.5,-9.1,-189.3,3.6,-180.8,10.3,1.5,1.80,0.09,0.46,15.52,4.51,7.89,9.15
121,NGC 6934,NaN,20:34:11.37,+07:24:16.1,52.10,-18.89,15.6,12.8,9.1,11.7,-5.1,-411.4,1.6,-398.5,5.1,1.1,1.53,0.22,0.69,17.35,3.44,8.20,9.04
122,NGC 6981,M 72,20:53:27.70,-12:32:14.3,35.16,-32.68,17.0,12.9,11.7,8.3,-9.2,-345.0,3.7,-336.2,NaN,NaN,1.21,0.46,0.93,19.02,2.38,8.72,9.23
123,NGC 7006,NaN,21:01:29.38,+16:11:14.4,63.77,-19.41,41.2,38.5,17.2,34.8,-13.7,-384.1,0.4,-371.3,NaN,NaN,1.41,0.17,0.44,18.62,2.58,8.66,9.42
124,NGC 7078,M 15,21:29:58.33,+12:10:01.2,65.01,-27.31,10.4,10.4,3.9,8.3,-4.8,-107.0,0.2,-96.0,13.5,0.9,2.29,0.14,1.00,14.21,5.05,7.84,9.32
125,NGC 7089,M 2,21:33:27.02,-00:49:23.7,53.37,-35.77,11.5,10.4,5.6,7.5,-6.7,-5.3,2.0,3.8,8.2,0.6,1.59,0.32,1.06,15.78,4.00,8.48,9.40
126,NGC 7099,M 30,21:40:22.12,-23:10:47.5,27.18,-46.84,8.1,7.1,4.9,2.5,-5.9,-184.2,0.2,-179.6,5.5,0.4,2.50,0.06,1.03,15.35,5.01,6.37,8.88
127,NGC 7492,NaN,23:08:26.63,-15:36:41.4,53.39,-63.48,26.3,25.3,7.0,9.4,-23.5,-177.5,0.6,-176.2,1.2,1.0,0.72,0.86,1.15,20.68,1.27,9.60,9.44
128,Pal 1,NaN,03:33:20.04,+79:34:51.8,130.06,19.03,11.1,17.2,-6.8,8.1,3.6,-82.8,3.3,-76.2,NaN,NaN,2.57,0.01,0.46,20.93,3.51,4.06,7.76
129,Pal 10,NaN,19:18:02.1,+18:34:18,52.43,2.72,5.9,6.4,3.6,4.7,0.3,-31.7,0.4,-15.6,NaN,NaN,0.58,0.81,0.99,22.03,3.51,8.69,8.37
130,Pal 11,NaN,19:45:14.4,-08:00:26,31.81,-15.57,13.4,8.2,11.0,6.8,-3.6,-68.0,10.0,-56.0,NaN,NaN,0.57,1.19,1.46,19.72,2.29,9.61,9.34
131,Pal 12,NaN,21:46:38.84,-21:15:09.4,30.51,-47.68,19.0,15.8,11.0,6.5,-14.1,27.8,1.5,32.5,NaN,NaN,2.98,0.02,1.72,19.21,3.64,5.22,9.28
132,Pal 13,NaN,23:06:44.44,+12:46:19.2,87.10,-42.70,26.0,26.9,1.0,19.1,-17.6,25.2,0.3,30.9,0.9,0.3,0.66,0.48,0.36,24.31,0.16,8.36,8.35
133,Pal 14,AvdB,16:11:00.6,+14:57:28,28.74,42.19,76.5,71.6,49.7,27.3,51.4,72.3,0.2,87.0,0.4,0.1,0.80,0.82,1.22,25.25,-0.97,9.85,10.02
134,Pal 15,NaN,16:59:51.0,-00:32:20,18.88,24.30,45.1,38.4,38.9,13.3,18.6,68.9,1.1,82.9,NaN,NaN,0.60,1.20,1.10,24.87,-0.25,9.99,9.72
135,Pal 2,NaN,04:46:05.91,+31:22:53.4,170.53,-9.07,27.2,35.0,-26.4,4.4,-4.3,-133.0,57.0,-140.1,NaN,NaN,1.53,0.17,0.50,19.06,4.06,8.82,9.28
136,Pal 3,NaN,10:05:31.9,+00:04:18,240.15,41.86,92.5,95.7,-34.3,-59.7,61.7,83.4,8.4,75.9,NaN,NaN,0.99,0.41,0.65,23.26,0.01,9.65,9.88
137,Pal 4,NaN,11:29:16.80,+28:58:24.9,202.31,71.80,108.7,111.2,-31.4,-12.9,103.2,74.5,2.1,76.6,NaN,NaN,0.93,0.33,0.51,23.01,0.11,9.72,9.42
138,Pal 5,NaN,15:16:05.25,-00:06:41.8,0.85,45.86,23.2,18.6,16.2,0.2,16.7,-58.7,0.2,-48.0,1.1,0.2,0.52,2.29,2.73,24.64,-0.58,9.81,9.82
139,Pal 6,NaN,17:43:42.2,-26:13:21,2.10,1.78,5.8,2.2,5.8,0.2,0.2,181.0,2.8,190.2,NaN,NaN,1.10,0.66,1.20,21.51,3.46,8.34,8.64
140,Pal 8,NaN,18:41:29.9,-19:49:33,14.11,-6.79,12.8,5.5,12.3,3.1,-1.5,-43.0,15.0,-32.3,NaN,NaN,1.53,0.56,0.58,20.00,2.34,8.65,8.47
141,Pyxis,NaN,09:07:57.8,-37:13:17,261.32,7.00,39.4,41.4,-5.9,-38.7,4.8,34.3,1.9,20.7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
142,Rup 106,NaN,12:38:40.2,-51:09:01,300.88,11.67,21.2,18.5,10.7,-17.8,4.3,-44.0,3.0,-49.7,NaN,NaN,0.70,1.00,1.05,21.82,1.10,9.41,9.34
143,Terzan 1,HP 2,17:35:47.8,-30:28:11,357.57,1.00,6.7,1.3,6.7,-0.3,0.1,114.0,14.0,122.0,NaN,NaN,2.50,0.04,3.82,25.09,3.85,4.99,9.12
144,Terzan 10,NaN,18:03:36.4,-26:04:21,4.49,-1.99,5.8,2.3,5.8,0.5,-0.2,NaN,NaN,NaN,NaN,NaN,0.75,0.90,1.55,21.28,4.64,9.34,8.74
145,Terzan 12,NaN,18:12:15.8,-22:44:31,8.37,-2.10,4.8,3.4,4.7,0.7,-0.2,94.1,1.5,104.2,NaN,NaN,0.57,0.83,0.75,23.75,3.40,8.46,7.78
146,Terzan 2,HP 3,17:27:33.10,-30:48:08.4,356.32,2.30,7.5,0.8,7.5,-0.5,0.3,109.0,15.0,116.9,NaN,NaN,2.50,0.03,1.52,22.16,4.86,5.46,8.82
147,Terzan 3,NaN,16:28:40.08,-35:21:12.5,345.08,9.19,8.2,2.5,7.8,-2.1,1.3,-136.3,0.7,-130.6,NaN,NaN,0.70,1.18,1.25,22.52,1.82,8.79,8.57

Function to normalise ID names

In [7]:
def normalise_IDs(id_string):
    """
    Normalises the IDs in the given DataFrame to match the IDs in the VDB and Krause21 datasets.
    Strip 'NGC prefix' from the Harris IDs to match the VDB and Krause21 IDs.
    If the ID column starts with 'NGC', remove the 'NGC' prefix and any leading/trailing whitespace.
    Returns the numerical part of the ID as an integer.
    if the ID column does not start with 'NGC', return the ID as is.

    """
    if id_string.startswith('NGC'):
        return int(id_string[3:].strip())
    else:
        return np.nan  # Return NaN for IDs that do not start with 'NGC'

In [9]:
ngc_numbers = []
for id_val in harris_merged['ID']:
    ngc_numbers.append(normalise_IDs(id_val))
harris_merged['NGC_number'] = ngc_numbers
display(harris_merged)

,ID,Name,RA,DEC,L,B,R_Sun,R_gc,X,Y,Z,v_r,v_r_e,v_LSR,sig_v,sig_v_e,c,r_c,r_h,mu_V,rho_0,lg_tc,lg_th,NGC_number
0,1636-283,ESO452-SC11,16:39:25.45,-28:23:55.3,351.91,12.10,8.3,2.1,8.0,-1.1,1.7,NaN,NaN,NaN,NaN,NaN,1.00,0.50,0.50,20.75,2.50,8.07,7.87,NaN
1,2MS-GC01,2MASS-GC01,18:08:21.81,-19:49:47,10.48,0.11,3.6,4.5,3.5,0.7,0.0,NaN,NaN,NaN,NaN,NaN,0.85,0.85,1.65,NaN,NaN,NaN,8.43,NaN
2,2MS-GC02,2MASS-GC02,18:09:36.50,-20:46:44,9.79,-0.61,4.9,3.2,4.9,0.8,-0.1,-238.0,36.0,-227.4,NaN,NaN,0.95,0.55,0.55,NaN,NaN,NaN,7.72,NaN
3,AM 1,E 1,03:55:02.3,-49:36:55,258.34,-48.47,123.3,124.6,-16.5,-80.1,-92.3,116.0,20.0,101.3,NaN,NaN,1.36,0.17,0.41,23.62,0.03,8.96,9.61,NaN
4,AM 4,NaN,13:56:21.7,-27:10:03,320.28,33.51,32.2,27.8,20.7,-17.2,17.8,NaN,NaN,NaN,NaN,NaN,0.70,0.41,0.43,24.75,-0.05,8.42,8.32,NaN
5,Arp 2,NaN,19:28:44.11,-30:21:20.3,8.55,-20.79,28.6,21.4,26.4,4.0,-10.2,115.0,10.0,122.4,NaN,NaN,0.88,1.19,1.77,24.26,-0.25,9.39,9.70,NaN
6,BH 176,NaN,15:39:07.45,-50:03:09.8,328.41,4.34,18.9,12.9,16.1,-9.9,1.4,NaN,NaN,NaN,NaN,NaN,0.85,0.90,0.90,23.36,0.97,9.14,8.79,NaN
7,BH 261,AL 3,18:14:06.6,-28:38:06,3.36,-5.27,6.5,1.7,6.5,0.4,-0.6,NaN,NaN,NaN,NaN,NaN,1.00,0.40,0.55,NaN,NaN,NaN,7.80,NaN
8,Djorg 1,NaN,17:47:28.3,-33:03:56,356.69,-2.47,13.7,5.7,13.6,-0.8,-0.6,-362.4,3.6,-355.0,NaN,NaN,1.50,0.50,1.59,23.10,2.68,8.71,0.00,NaN
9,Djorg 2,ESO456-SC38,18:01:49.1,-27:49:33,2.77,-2.50,6.3,1.8,6.2,0.3,-0.3,NaN,NaN,NaN,NaN,NaN,1.50,0.33,1.05,19.50,3.85,7.73,0.00,NaN
10,E 3,NaN,09:20:57.07,-77:16:54.8,292.27,-19.02,8.1,9.1,2.9,-7.1,-2.6,NaN,NaN,NaN,NaN,NaN,0.75,1.87,2.10,23.10,0.84,8.93,8.80,NaN
11,ESO-SC06,ESO280-SC06,18:09:06.0,-46:25:23,346.90,-12.57,21.4,14.0,20.4,-4.7,-4.7,NaN,NaN,NaN,NaN,NaN,0.90,0.60,1.05,NaN,NaN,NaN,9.10,NaN
12,Eridanus,NaN,04:24:44.5,-21:11:13,218.10,-41.33,90.1,95.0,-53.2,-41.7,-59.5,-23.6,2.1,-39.1,NaN,NaN,1.10,0.25,0.46,22.81,0.38,9.18,9.54,NaN
13,FSR 1735,NaN,16:52:10.6,-47:03:29,339.19,-1.85,9.8,3.7,9.1,-3.5,-0.3,NaN,NaN,NaN,NaN,NaN,0.56,0.39,0.34,NaN,NaN,NaN,8.11,NaN
14,GLIMPSE01,NaN,18:48:49.7,-01:29:50,31.31,-0.10,4.2,4.9,3.6,2.2,0.0,NaN,NaN,NaN,NaN,NaN,1.37,0.59,0.65,NaN,NaN,NaN,7.89,NaN
15,GLIMPSE02,NaN,18:18:30.5,-16:58:38,14.14,-0.64,5.5,3.0,5.4,1.4,-0.1,NaN,NaN,NaN,NaN,NaN,1.33,0.70,NaN,NaN,NaN,NaN,NaN,NaN
16,HP 1,BH 229,17:31:05.2,-29:58:54,357.44,2.12,8.2,0.5,8.2,-0.4,0.3,45.8,0.7,54.0,NaN,NaN,2.50,0.03,3.10,21.29,4.33,5.03,9.44,NaN
17,IC 1257,NaN,17:27:08.5,-07:05:35,16.54,15.15,25.0,17.9,23.2,6.9,6.5,-140.2,2.1,-127.0,NaN,NaN,1.55,0.25,1.40,NaN,NaN,NaN,9.60,NaN
18,IC 1276,Pal 7,18:10:44.20,-07:12:27.4,21.83,5.67,5.4,3.7,5.0,2.0,0.5,155.7,1.3,169.2,NaN,NaN,1.33,1.01,2.38,21.60,2.78,8.46,9.03,NaN
19,IC 4499,NaN,15:00:18.45,-82:12:49.3,307.35,-20.47,18.8,15.7,10.7,-14.0,-6.6,31.5,0.2,24.1,2.5,0.5,1.21,0.84,1.71,20.90,1.55,9.21,9.73,NaN
20,Ko 1,NaN,11:59:18.5,+12:15:36,260.99,70.75,48.3,49.3,-2.5,-15.7,45.6,NaN,NaN,NaN,NaN,NaN,0.50,0.33,0.26,NaN,NaN,NaN,8.62,NaN
21,Ko 2,NaN,07:58:17.0,+26:15:18,195.12,25.54,34.7,41.9,-30.2,-8.2,15.0,NaN,NaN,NaN,NaN,NaN,0.50,0.25,0.21,NaN,NaN,NaN,7.70,NaN
22,Liller 1,NaN,17:33:24.50,-33:23:20.4,354.84,-0.16,8.2,0.8,8.2,-0.7,0.0,52.0,15.0,59.2,NaN,NaN,2.30,0.06,NaN,24.00,5.28,6.62,0.00,NaN
23,Lynga 7,BH184,16:11:03.65,-55:19:04.0,328.77,-2.80,8.0,4.3,6.8,-4.1,-0.4,8.0,5.0,8.0,NaN,NaN,0.95,0.90,1.20,NaN,NaN,NaN,8.83,NaN
24,NGC 104,47 Tuc,00:24:05.67,-72:04:52.6,305.89,-44.89,4.5,7.4,1.9,-2.6,-3.1,-18.0,0.1,-26.7,11.0,0.3,2.07,0.36,3.17,14.38,4.88,7.84,9.55,104.0
25,NGC 1261,NaN,03:12:16.21,-55:12:58.4,270.54,-52.12,16.3,18.1,0.1,-10.0,-12.9,68.2,4.6,54.9,NaN,NaN,1.16,0.35,0.68,17.73,2.99,8.59,9.12,1261.0
26,NGC 1851,NaN,05:14:06.76,-40:02:47.6,244.51,-35.03,12.1,16.6,-4.2,-8.9,-6.9,320.5,0.6,303.8,10.4,0.5,1.86,0.09,0.51,14.25,5.09,7.43,8.82,1851.0
27,NGC 1904,M 79,05:24:11.09,-24:31:29.0,227.23,-29.35,12.9,18.8,-7.7,-8.3,-6.3,205.8,0.4,189.0,5.3,0.4,1.70,0.16,0.65,16.02,4.08,7.83,8.95,1904.0
28,NGC 2298,NaN,06:48:59.41,-36:00:19.1,245.63,-16.00,10.8,15.8,-4.3,-9.4,-3.0,148.9,1.2,132.0,NaN,NaN,1.38,0.31,0.98,18.90,2.90,7.91,8.84,2298.0
29,NGC 2419,NaN,07:38:08.47,+38:52:56.8,180.37,25.24,82.6,89.9,-74.7,-0.5,35.2,-20.2,0.5,-25.2,4.0,0.6,1.37,0.32,0.89,19.67,1.62,9.87,10.63,2419.0
30,NGC 2808,NaN,09:12:03.10,-64:51:48.6,282.19,-11.25,9.6,11.1,2.0,-9.2,-1.9,101.6,0.7,89.2,13.4,1.2,1.56,0.25,0.80,15.08,4.66,8.24,9.15,2808.0
31,NGC 288,NaN,00:52:45.24,-26:34:57.4,152.30,-89.38,8.9,12.0,-0.1,0.0,-8.9,-45.4,0.2,-51.9,2.9,0.3,0.99,1.35,2.23,20.05,1.78,8.99,9.32,288.0
32,NGC 3201,NaN,10:17:36.82,-46:24:44.9,277.23,8.64,4.9,8.8,0.6,-4.8,0.7,494.0,0.2,482.9,5.0,0.2,1.29,1.30,3.10,19.00,2.71,8.61,9.27,3201.0
33,NGC 362,NaN,01:03:14.26,-70:50:55.6,301.53,-46.25,8.6,9.4,3.1,-5.1,-6.2,223.5,0.5,214.0,6.4,0.3,1.76,0.18,0.82,14.80,4.74,7.76,8.93,362.0
34,NGC 4147,NaN,12:10:06.30,+18:32:33.5,252.85,77.19,19.3,21.4,-1.3,-4.1,18.8,183.2,0.7,186.1,2.6,0.7,1.83,0.09,0.48,17.38,3.63,7.41,8.74,4147.0
35,NGC 4372,NaN,12:25:45.40,-72:39:32.4,300.99,-9.88,5.8,7.1,2.9,-4.9,-1.0,72.3,1.2,64.2,NaN,NaN,1.30,1.75,3.91,20.58,2.06,8.88,9.59,4372.0
36,NGC 4590,M 68,12:39:27.98,-26:44:38.6,299.63,36.05,10.3,10.2,4.1,-7.2,6.0,-94.7,0.2,-96.8,2.5,0.4,1.41,0.58,1.51,18.81,2.57,8.45,9.27,4590.0
37,NGC 4833,NaN,12:59:33.92,-70:52:35.4,303.60,-8.02,6.6,7.0,3.6,-5.4,-0.9,200.2,1.2,192.9,NaN,NaN,1.25,1.00,2.41,18.48,3.00,8.78,9.42,4833.0
38,NGC 5024,M 53,13:12:55.25,+18:10:05.4,332.96,79.76,17.9,18.4,2.8,-1.4,17.6,-62.9,0.3,-56.2,4.4,0.9,1.72,0.35,1.31,17.38,3.07,8.73,9.76,5024.0
39,NGC 5053,NaN,13:16:27.09,+17:42:00.9,335.70,78.95,17.4,17.8,3.0,-1.4,17.1,44.0,0.4,50.9,1.4,0.2,0.74,2.08,2.61,22.03,0.54,9.81,9.87,5053.0
40,NGC 5139,omega Cen,13:26:47.24,-47:28:46.5,309.10,14.97,5.2,6.4,3.1,-3.9,1.3,232.1,0.1,228.9,16.8,0.3,1.31,2.37,5.00,16.81,3.15,9.60,10.09,5139.0
41,NGC 5272,M 3,13:42:11.62,+28:22:38.2,42.22,78.71,10.2,12.0,1.5,1.3,10.0,-147.6,0.2,-138.3,5.5,0.3,1.89,0.37,2.31,16.64,3.57,8.31,9.79,5272.0
42,NGC 5286,NaN,13:46:26.81,-51:22:27.3,311.61,10.57,11.7,8.9,7.6,-8.6,2.1,57.4,1.5,54.3,8.1,1.0,1.41,0.28,0.73,16.22,4.10,8.40,9.11,5286.0
43,NGC 5466,NaN,14:05:27.29,+28:32:04.0,42.15,73.59,16.0,16.3,3.3,3.0,15.3,110.7,0.2,121.2,1.7,0.2,1.04,1.43,2.30,21.61,0.84,9.35,9.76,5466.0
44,NGC 5634,NaN,14:29:37.23,-05:58:35.1,342.21,49.26,25.2,21.2,15.7,-5.0,19.1,-45.1,6.6,-37.5,NaN,NaN,2.07,0.09,0.86,17.20,3.63,7.67,9.54,5634.0
45,NGC 5694,NaN,14:39:36.29,-26:32:20.2,331.06,30.36,35.0,29.4,26.4,-14.6,17.7,-140.3,0.8,-136.2,5.8,0.8,1.89,0.06,0.40,16.51,3.95,7.85,9.27,5694.0
46,NGC 5824,NaN,15:03:58.63,-33:04:05.6,332.56,22.07,32.1,25.9,26.4,-13.7,12.1,-27.5,1.5,-23.8,11.6,0.5,1.98,0.06,0.45,15.18,4.61,7.91,9.47,5824.0
47,NGC 5897,NaN,15:17:24.50,-21:00:37.0,342.95,30.29,12.5,7.4,10.3,-3.2,6.3,101.5,1.0,108.4,NaN,NaN,0.86,1.40,2.06,20.53,1.53,9.33,9.57,5897.0
48,NGC 5904,M 5,15:18:33.22,+02:04:51.7,3.86,46.80,7.5,6.2,5.1,0.3,5.5,53.2,0.4,64.3,5.5,0.4,1.73,0.44,1.77,16.09,3.88,8.28,9.41,5904.0
49,NGC 5927,NaN,15:28:00.69,-50:40:22.9,326.60,4.86,7.7,4.6,6.4,-4.2,0.7,-107.5,0.9,-107.2,NaN,NaN,1.60,0.42,1.10,16.91,4.09,8.39,8.94,5927.0
50,NGC 5946,NaN,15:35:28.52,-50:39:34.8,327.58,4.19,10.6,5.8,8.9,-5.6,0.8,128.4,1.8,128.9,4.0,2.9,2.50,0.08,0.89,17.19,4.68,6.90,8.91,5946.0
51,NGC 5986,NaN,15:46:03.00,-37:47:11.1,337.02,13.27,10.4,4.8,9.3,-4.0,2.4,88.9,3.7,92.9,NaN,NaN,1.23,0.47,0.98,17.67,3.41,8.58,9.18,5986.0
52,NGC 6093,M 80,16:17:02.41,-22:58:33.9,352.67,19.46,10.0,3.8,9.4,-1.2,3.3,8.1,1.5,16.7,12.4,0.6,1.68,0.15,0.61,15.11,4.79,7.78,8.80,6093.0
53,NGC 6101,NaN,16:25:48.12,-72:12:07.9,317.74,-15.82,15.4,11.2,11.0,-10.0,-4.2,361.4,1.7,357.0,NaN,NaN,0.80,0.97,1.05,20.29,1.65,9.21,9.22,6101.0
54,NGC 6121,M 4,16:23:35.22,-26:31:32.7,350.97,15.97,2.2,5.9,2.1,-0.3,0.6,70.7,0.2,78.6,4.0,0.2,1.65,1.16,4.33,17.95,3.64,7.90,8.93,6121.0
55,NGC 6139,NaN,16:27:40.37,-38:50:55.5,342.37,6.94,10.1,3.6,9.6,-3.0,1.2,6.7,6.0,11.5,NaN,NaN,1.86,0.15,0.85,17.20,4.67,7.66,9.05,6139.0
56,NGC 6144,NaN,16:27:13.86,-26:01:24.6,351.93,15.70,8.9,2.7,8.5,-1.2,2.4,193.8,0.6,201.9,NaN,NaN,1.55,0.94,1.63,20.05,2.31,8.78,9.14,6144.0
57,NGC 6171,M 107,16:32:31.86,-13:03:13.6,3.37,23.01,6.4,3.3,5.9,0.3,2.5,-34.1,0.3,-23.0,4.1,0.3,1.53,0.56,1.73,18.94,3.08,8.06,9.00,6171.0
58,NGC 6205,M 13,16:41:41.24,+36:27:35.5,59.01,40.91,7.1,8.4,2.8,4.6,4.7,-244.2,0.2,-228.0,7.1,0.4,1.53,0.62,1.69,16.59,3.55,8.51,9.30,6205.0
59,NGC 6218,M 12,16:47:14.18,-01:56:54.7,15.72,26.31,4.8,4.5,4.2,1.2,2.1,-41.4,0.2,-27.9,4.5,0.4,1.34,0.79,1.77,18.10,3.23,8.19,8.87,6218.0
60,NGC 6229,NaN,16:46:58.79,+47:31:39.9,73.64,40.31,30.5,29.8,6.5,22.3,19.7,-154.2,7.6,-138.4,NaN,NaN,1.50,0.12,0.36,16.77,3.54,8.30,9.15,6229.0
61,NGC 6235,NaN,16:53:25.31,-22:10:38.8,358.92,13.52,11.5,4.2,11.2,-0.2,2.7,87.3,3.4,96.8,NaN,NaN,1.53,0.33,1.00,19.12,2.97,8.08,8.89,6235.0
62,NGC 6254,M 10,16:57:09.05,-04:06:01.1,15.14,23.08,4.4,4.6,3.9,1.1,1.7,75.2,0.7,88.5,6.6,0.8,1.38,0.77,1.95,17.70,3.54,8.21,8.90,6254.0
63,NGC 6256,NaN,16:59:32.62,-37:07:17.0,347.79,3.31,10.3,3.0,10.0,-2.2,0.6,-101.4,1.9,-95.6,6.6,2.6,2.50,0.02,0.86,17.89,5.59,5.82,8.86,6256.0
64,NGC 6266,M 62,17:01:12.80,-30:06:49.4,353.57,7.32,6.8,1.7,6.7,-0.8,0.9,-70.1,1.4,-62.3,14.3,0.4,1.71,0.22,0.92,15.10,5.16,7.90,8.98,6266.0
65,NGC 6273,M 19,17:02:37.80,-26:16:04.7,356.87,9.38,8.8,1.7,8.7,-0.5,1.4,135.0,4.1,143.8,NaN,NaN,1.53,0.43,1.32,16.77,3.98,8.52,9.38,6273.0
66,NGC 6284,NaN,17:04:28.51,-24:45:53.5,358.35,9.94,15.3,7.5,15.0,-0.4,2.6,27.5,1.7,36.7,6.3,0.9,2.50,0.07,0.66,16.35,4.55,7.24,9.09,6284.0
67,NGC 6287,NaN,17:05:09.13,-22:42:30.1,0.13,11.02,9.4,2.1,9.2,0.0,1.8,-288.7,3.5,-279.1,NaN,NaN,1.38,0.29,0.74,18.32,3.78,8.06,8.75,6287.0
68,NGC 6293,NaN,17:10:10.20,-26:34:55.5,357.62,7.83,9.5,1.9,9.4,-0.4,1.3,-146.2,1.7,-137.4,7.7,1.3,2.50,0.05,0.89,15.72,5.31,6.38,8.94,6293.0
69,NGC 6304,NaN,17:14:32.25,-29:27:43.3,355.83,5.38,5.9,2.3,5.8,-0.4,0.6,-107.3,3.6,-99.3,NaN,NaN,1.80,0.21,1.42,17.20,4.49,7.36,8.85,6304.0
70,NGC 6316,NaN,17:16:37.30,-28:08:24.4,357.18,5.76,10.4,2.6,10.4,-0.5,1.0,71.4,8.9,79.9,NaN,NaN,1.65,0.17,0.65,17.44,4.23,7.71,8.89,6316.0
71,NGC 6325,NaN,17:17:59.21,-23:45:57.6,0.97,8.00,7.8,1.1,7.7,0.1,1.1,29.8,1.8,39.3,5.9,1.3,2.50,0.03,0.63,17.56,5.52,5.73,8.45,6325.0
72,NGC 6333,M 9,17:19:11.26,-18:30:57.4,5.54,10.71,7.9,1.7,7.7,0.7,1.5,229.1,7.0,239.8,NaN,NaN,1.25,0.45,0.96,17.39,3.78,8.36,8.90,6333.0
73,NGC 6341,M 92,17:17:07.39,+43:08:09.4,68.34,34.86,8.3,9.6,2.5,6.3,4.7,-120.0,0.1,-103.5,6.0,0.4,1.68,0.26,1.02,15.47,4.30,7.96,9.02,6341.0
74,NGC 6342,NaN,17:21:10.08,-19:35:14.7,4.90,9.72,8.5,1.7,8.4,0.7,1.4,115.7,1.4,126.3,5.2,2.1,2.50,0.05,0.73,16.97,4.97,6.16,8.51,6342.0
75,NGC 6352,NaN,17:25:29.11,-48:25:19.8,341.42,-7.17,5.6,3.3,5.3,-1.8,-0.7,-137.0,1.1,-134.1,NaN,NaN,1.10,0.83,2.05,18.17,3.17,8.46,8.92,6352.0
76,NGC 6355,NaN,17:23:58.59,-26:21:12.3,359.59,5.43,9.2,1.4,9.2,-0.1,0.9,-176.9,7.1,-167.9,NaN,NaN,2.50,0.05,0.88,17.64,5.04,6.27,8.96,6355.0
77,NGC 6356,NaN,17:23:34.93,-17:48:46.9,6.72,10.22,15.1,7.5,14.7,1.7,2.7,27.0,4.3,38.0,NaN,NaN,1.59,0.24,0.81,17.02,3.78,8.37,9.30,6356.0
78,NGC 6362,NaN,17:31:54.99,-67:02:54.0,325.55,-17.57,7.6,5.1,6.0,-4.1,-2.3,-13.1,0.6,-15.6,2.8,0.4,1.09,1.13,2.05,19.31,2.29,8.80,9.20,6362.0
79,NGC 6366,NaN,17:27:44.24,-05:04:47.5,18.41,16.04,3.5,5.0,3.2,1.1,1.0,-122.2,0.5,-108.6,1.3,0.5,0.74,2.17,2.92,21.25,2.39,8.74,8.73,6366.0
80,NGC 6380,Ton 1,17:34:28.0,-39:04:09,350.18,-3.42,10.9,3.3,10.7,-1.9,-0.6,-3.6,2.5,2.1,NaN,NaN,1.55,0.34,0.74,19.89,3.73,8.40,8.86,6380.0
81,NGC 6388,NaN,17:36:17.23,-44:44:07.8,345.56,-6.74,9.9,3.1,9.6,-2.5,-1.2,80.1,0.8,84.2,18.9,0.8,1.75,0.12,0.52,14.49,5.37,7.72,8.90,6388.0
82,NGC 6397,NaN,17:40:42.09,-53:40:27.6,338.17,-11.96,2.3,6.0,2.1,-0.8,-0.5,18.8,0.1,20.3,4.5,0.2,2.50,0.05,2.90,15.47,5.76,4.94,8.60,6397.0
83,NGC 6401,NaN,17:38:36.60,-23:54:34.2,3.45,3.98,10.6,2.7,10.5,0.6,0.7,-65.0,8.6,-55.3,NaN,NaN,1.69,0.25,1.91,18.70,3.79,7.97,9.53,6401.0
84,NGC 6402,M 14,17:37:36.10,-03:14:45.3,21.32,14.81,9.3,4.0,8.3,3.3,2.4,-66.1,1.8,-52.1,NaN,NaN,0.99,0.79,1.30,18.41,3.36,9.06,9.39,6402.0
85,NGC 6426,NaN,17:44:54.65,+03:10:12.5,28.09,16.23,20.6,14.4,17.4,9.3,5.8,-162.0,23.0,-146.9,NaN,NaN,1.70,0.26,0.92,20.09,2.47,8.31,9.28,6426.0
86,NGC 6440,NaN,17:48:52.70,-20:21:36.9,7.73,3.80,8.5,1.3,8.4,1.1,0.6,-76.6,2.7,-65.9,NaN,NaN,1.62,0.14,0.48,17.06,5.24,7.60,8.62,6440.0
87,NGC 6441,NaN,17:50:13.06,-37:03:05.2,353.53,-5.01,11.6,3.9,11.5,-1.3,-1.0,16.5,1.0,22.9,18.0,0.2,1.74,0.13,0.57,14.85,5.26,7.93,9.09,6441.0
88,NGC 6453,NaN,17:50:51.70,-34:35:57.0,355.72,-3.87,11.6,3.7,11.5,-0.9,-0.8,-83.7,8.3,-76.7,NaN,NaN,2.50,0.05,0.44,17.07,4.95,6.73,8.52,6453.0
89,NGC 6496,NaN,17:59:03.68,-44:15:57.4,348.03,-10.01,11.3,4.2,10.9,-2.3,-2.0,-112.7,5.7,-108.4,NaN,NaN,0.70,0.95,1.02,20.17,1.99,8.94,9.04,6496.0
90,NGC 6517,NaN,18:01:50.52,-08:57:31.6,19.23,6.76,10.6,4.2,10.0,3.5,1.3,-39.6,8.0,-26.5,NaN,NaN,1.82,0.06,0.50,17.56,5.29,6.92,8.72,6517.0
91,NGC 6522,NaN,18:03:34.02,-30:02:02.3,1.02,-3.93,7.7,0.6,7.7,0.1,-0.5,-21.1,3.4,-12.9,6.7,0.7,2.50,0.05,1.00,15.75,5.48,6.38,8.86,6522.0
92,NGC 6528,NaN,18:04:49.64,-30:03:22.6,1.14,-4.17,7.9,0.6,7.9,0.2,-0.6,206.6,1.4,214.9,NaN,NaN,1.50,0.13,0.38,16.73,4.77,7.28,8.06,6528.0
93,NGC 6535,NaN,18:03:50.51,-00:17:51.5,27.18,10.44,6.8,3.9,6.0,3.1,1.2,-215.1,0.5,-200.4,2.4,0.5,1.33,0.36,0.85,21.26,2.34,7.28,8.20,6535.0
94,NGC 6539,NaN,18:04:49.68,-07:35:09.1,20.80,6.78,7.8,3.0,7.2,2.8,0.9,31.0,1.7,44.4,NaN,NaN,1.74,0.38,1.70,18.58,4.15,8.31,9.32,6539.0
95,NGC 6540,Djorg 3,18:06:08.6,-27:45:55,3.29,-3.31,5.3,2.8,5.2,0.3,-0.3,-17.7,1.4,-8.8,NaN,NaN,2.50,0.03,NaN,16.40,5.85,5.40,0.00,6540.0
96,NGC 6541,NaN,18:08:02.36,-43:42:53.6,349.29,-11.19,7.5,2.1,7.3,-1.4,-1.5,-158.7,2.3,-154.2,8.2,2.1,1.86,0.18,1.06,15.44,4.65,7.55,9.03,6541.0
97,NGC 6544,NaN,18:07:20.58,-24:59:50.4,5.84,-2.20,3.0,5.1,2.9,0.3,-0.1,-27.3,3.9,-17.7,NaN,NaN,1.63,0.05,1.21,16.31,6.06,5.35,8.24,6544.0
98,NGC 6553,NaN,18:09:17.60,-25:54:31.3,5.26,-3.03,6.0,2.2,5.9,0.5,-0.3,-3.2,1.5,6.1,NaN,NaN,1.16,0.53,1.03,18.17,3.84,8.24,8.72,6553.0
99,NGC 6558,NaN,18:10:17.60,-31:45:50.0,0.20,-6.02,7.4,1.0,7.3,0.0,-0.8,-197.2,1.5,-189.4,3.1,0.9,2.50,0.03,2.15,16.48,5.35,5.71,9.12,6558.0
100,NGC 6569,NaN,18:13:38.80,-31:49:36.8,0.48,-6.68,10.9,3.1,10.8,0.1,-1.3,-28.1,5.6,-20.3,NaN,NaN,1.31,0.35,0.80,18.15,3.63,8.38,9.05,6569.0
101,NGC 6584,NaN,18:18:37.60,-52:12:56.8,342.14,-16.41,13.5,7.0,12.3,-4.0,-3.8,222.9,15.0,224.9,NaN,NaN,1.47,0.26,0.73,17.63,3.33,8.13,9.02,6584.0
102,NGC 6624,NaN,18:23:40.51,-30:21:39.7,2.79,-7.91,7.9,1.2,7.8,0.4,-1.1,53.9,0.6,62.1,5.4,0.5,2.50,0.06,0.82,15.32,5.30,6.61,8.71,6624.0
103,NGC 6626,M 28,18:24:32.81,-24:52:11.2,7.80,-5.58,5.5,2.7,5.4,0.7,-0.5,17.0,1.0,26.6,8.6,1.3,1.67,0.24,1.97,15.77,4.86,7.62,9.17,6626.0
104,NGC 6637,M 69,18:31:23.10,-32:20:53.1,1.72,-10.27,8.8,1.7,8.6,0.3,-1.6,39.9,2.8,47.5,NaN,NaN,1.38,0.33,0.84,16.82,3.84,8.15,8.82,6637.0
105,NGC 6638,NaN,18:30:56.10,-25:29:50.9,7.90,-7.15,9.4,2.2,9.3,1.3,-1.2,18.1,3.9,27.5,NaN,NaN,1.33,0.22,0.51,17.30,4.09,7.83,8.46,6638.0
106,NGC 6642,NaN,18:31:54.10,-23:28:30.7,9.81,-6.44,8.1,1.7,8.0,1.4,-0.9,-57.2,5.4,-47.3,NaN,NaN,1.99,0.10,0.73,16.82,4.64,6.95,8.52,6642.0
107,NGC 6652,NaN,18:35:45.63,-32:59:26.6,1.53,-11.38,10.0,2.7,9.8,0.3,-2.0,-111.7,5.8,-104.3,NaN,NaN,1.80,0.10,0.48,16.10,4.48,7.05,8.39,6652.0
108,NGC 6656,M 22,18:36:23.94,-23:54:17.1,9.89,-7.55,3.2,4.9,3.2,0.6,-0.4,-146.3,0.2,-136.6,7.8,0.3,1.38,1.33,3.36,17.42,3.63,8.53,9.23,6656.0
109,NGC 6681,M 70,18:43:12.76,-32:17:31.6,2.85,-12.51,9.0,2.2,8.8,0.4,-2.0,220.3,0.9,227.8,5.2,0.5,2.50,0.03,0.71,14.25,5.82,5.82,8.65,6681.0
110,NGC 6712,NaN,18:53:04.30,-08:42:22.0,25.35,-4.32,6.9,3.5,6.3,3.0,-0.5,-107.6,0.5,-94.7,4.3,0.4,1.05,0.76,1.33,18.74,3.18,8.60,8.95,6712.0
111,NGC 6715,M 54,18:55:03.33,-30:28:47.5,5.61,-14.09,26.5,18.9,25.6,2.5,-6.5,141.3,0.3,149.2,10.5,0.3,2.04,0.09,0.82,14.78,4.69,8.24,9.93,6715.0
112,NGC 6717,Pal 9,18:55:06.04,-22:42:05.3,12.88,-10.90,7.1,2.4,6.8,1.6,-1.3,22.8,3.4,32.7,NaN,NaN,2.07,0.08,0.68,16.77,4.58,6.52,8.22,6717.0
113,NGC 6723,NaN,18:59:33.15,-36:37:56.1,0.07,-17.30,8.7,2.6,8.3,0.0,-2.6,-94.5,3.6,-88.3,NaN,NaN,1.11,0.83,1.53,18.13,2.79,8.79,9.24,6723.0
114,NGC 6749,NaN,19:05:15.3,+01:54:03,36.20,-2.21,7.9,5.0,6.4,4.7,-0.3,-61.7,2.9,-47.2,NaN,NaN,0.79,0.62,1.10,21.88,3.30,8.59,8.78,6749.0
115,NGC 6752,NaN,19:10:52.11,-59:59:04.4,336.49,-25.63,4.0,5.2,3.3,-1.4,-1.7,-26.7,0.2,-27.3,4.9,0.4,2.50,0.17,1.91,14.88,5.04,6.88,8.87,6752.0
116,NGC 6760,NaN,19:11:12.01,+01:01:49.7,36.11,-3.92,7.4,4.8,5.9,4.3,-0.5,-27.5,6.3,-13.2,NaN,NaN,1.65,0.34,1.27,18.66,3.89,7.96,9.01,6760.0
117,NGC 6779,M 56,19:16:35.57,+30:11:00.5,62.66,8.34,9.4,9.2,4.3,8.3,1.4,-135.6,0.9,-119.1,4.0,0.6,1.38,0.44,1.10,18.08,3.28,8.33,9.01,6779.0
118,NGC 6809,M 55,19:39:59.71,-30:57:53.1,8.79,-23.27,5.4,3.9,4.9,0.8,-2.1,174.7,0.3,181.8,4.0,0.3,0.93,1.80,2.83,19.36,2.22,8.90,9.29,6809.0
119,NGC 6838,M 71,19:53:46.49,+18:46:45.1,56.75,-4.56,4.0,6.7,2.2,3.4,-0.3,-22.8,0.2,-7.5,2.3,0.2,1.15,0.63,1.67,19.75,2.83,7.54,8.43,6838.0
120,NGC 6864,M 75,20:06:04.69,-21:55:16.2,20.30,-25.75,20.9,14.7,17.6,6.5,-9.1,-189.3,3.6,-180.8,10.3,1.5,1.80,0.09,0.46,15.52,4.51,7.89,9.15,6864.0
121,NGC 6934,NaN,20:34:11.37,+07:24:16.1,52.10,-18.89,15.6,12.8,9.1,11.7,-5.1,-411.4,1.6,-398.5,5.1,1.1,1.53,0.22,0.69,17.35,3.44,8.20,9.04,6934.0
122,NGC 6981,M 72,20:53:27.70,-12:32:14.3,35.16,-32.68,17.0,12.9,11.7,8.3,-9.2,-345.0,3.7,-336.2,NaN,NaN,1.21,0.46,0.93,19.02,2.38,8.72,9.23,6981.0
123,NGC 7006,NaN,21:01:29.38,+16:11:14.4,63.77,-19.41,41.2,38.5,17.2,34.8,-13.7,-384.1,0.4,-371.3,NaN,NaN,1.41,0.17,0.44,18.62,2.58,8.66,9.42,7006.0
124,NGC 7078,M 15,21:29:58.33,+12:10:01.2,65.01,-27.31,10.4,10.4,3.9,8.3,-4.8,-107.0,0.2,-96.0,13.5,0.9,2.29,0.14,1.00,14.21,5.05,7.84,9.32,7078.0
125,NGC 7089,M 2,21:33:27.02,-00:49:23.7,53.37,-35.77,11.5,10.4,5.6,7.5,-6.7,-5.3,2.0,3.8,8.2,0.6,1.59,0.32,1.06,15.78,4.00,8.48,9.40,7089.0
126,NGC 7099,M 30,21:40:22.12,-23:10:47.5,27.18,-46.84,8.1,7.1,4.9,2.5,-5.9,-184.2,0.2,-179.6,5.5,0.4,2.50,0.06,1.03,15.35,5.01,6.37,8.88,7099.0
127,NGC 7492,NaN,23:08:26.63,-15:36:41.4,53.39,-63.48,26.3,25.3,7.0,9.4,-23.5,-177.5,0.6,-176.2,1.2,1.0,0.72,0.86,1.15,20.68,1.27,9.60,9.44,7492.0
128,Pal 1,NaN,03:33:20.04,+79:34:51.8,130.06,19.03,11.1,17.2,-6.8,8.1,3.6,-82.8,3.3,-76.2,NaN,NaN,2.57,0.01,0.46,20.93,3.51,4.06,7.76,NaN
129,Pal 10,NaN,19:18:02.1,+18:34:18,52.43,2.72,5.9,6.4,3.6,4.7,0.3,-31.7,0.4,-15.6,NaN,NaN,0.58,0.81,0.99,22.03,3.51,8.69,8.37,NaN
130,Pal 11,NaN,19:45:14.4,-08:00:26,31.81,-15.57,13.4,8.2,11.0,6.8,-3.6,-68.0,10.0,-56.0,NaN,NaN,0.57,1.19,1.46,19.72,2.29,9.61,9.34,NaN
131,Pal 12,NaN,21:46:38.84,-21:15:09.4,30.51,-47.68,19.0,15.8,11.0,6.5,-14.1,27.8,1.5,32.5,NaN,NaN,2.98,0.02,1.72,19.21,3.64,5.22,9.28,NaN
132,Pal 13,NaN,23:06:44.44,+12:46:19.2,87.10,-42.70,26.0,26.9,1.0,19.1,-17.6,25.2,0.3,30.9,0.9,0.3,0.66,0.48,0.36,24.31,0.16,8.36,8.35,NaN
133,Pal 14,AvdB,16:11:00.6,+14:57:28,28.74,42.19,76.5,71.6,49.7,27.3,51.4,72.3,0.2,87.0,0.4,0.1,0.80,0.82,1.22,25.25,-0.97,9.85,10.02,NaN
134,Pal 15,NaN,16:59:51.0,-00:32:20,18.88,24.30,45.1,38.4,38.9,13.3,18.6,68.9,1.1,82.9,NaN,NaN,0.60,1.20,1.10,24.87,-0.25,9.99,9.72,NaN
135,Pal 2,NaN,04:46:05.91,+31:22:53.4,170.53,-9.07,27.2,35.0,-26.4,4.4,-4.3,-133.0,57.0,-140.1,NaN,NaN,1.53,0.17,0.50,19.06,4.06,8.82,9.28,NaN
136,Pal 3,NaN,10:05:31.9,+00:04:18,240.15,41.86,92.5,95.7,-34.3,-59.7,61.7,83.4,8.4,75.9,NaN,NaN,0.99,0.41,0.65,23.26,0.01,9.65,9.88,NaN
137,Pal 4,NaN,11:29:16.80,+28:58:24.9,202.31,71.80,108.7,111.2,-31.4,-12.9,103.2,74.5,2.1,76.6,NaN,NaN,0.93,0.33,0.51,23.01,0.11,9.72,9.42,NaN
138,Pal 5,NaN,15:16:05.25,-00:06:41.8,0.85,45.86,23.2,18.6,16.2,0.2,16.7,-58.7,0.2,-48.0,1.1,0.2,0.52,2.29,2.73,24.64,-0.58,9.81,9.82,NaN
139,Pal 6,NaN,17:43:42.2,-26:13:21,2.10,1.78,5.8,2.2,5.8,0.2,0.2,181.0,2.8,190.2,NaN,NaN,1.10,0.66,1.20,21.51,3.46,8.34,8.64,NaN
140,Pal 8,NaN,18:41:29.9,-19:49:33,14.11,-6.79,12.8,5.5,12.3,3.1,-1.5,-43.0,15.0,-32.3,NaN,NaN,1.53,0.56,0.58,20.00,2.34,8.65,8.47,NaN

In [ ]:
display(VDB['#NGC'].dtype)
display(VDB['#NGC'].head())
VDB['NGC_number'] = pd.to_numeric(VDB['#NGC'], errors='coerce') # Get rid of the "XXXX" in ID datafield

0     104
1     288
2     362
3    1261
4    1851
Name: #NGC, dtype: str

In [20]:
# Merge the Harris and VDB datasets on the NGC_number column
harris_vdb = pd.merge(harris_merged, VDB, on='NGC_number', how='outer')

display(np.nan == np.nan)

False